name: Linter

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install cpplint
      run: pip install cpplint
    - name: Run linter
      run: cpplint --recursive */*
