name: Linter

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install and run cpplint
      run: pip install cpplint && cpplint --recursive */*
