name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Testing
      uses: ./
      with:
        entrypoint: /src/build/test/ExampleProject_test
